### PR TITLE
Refactor Albums and Implement Album Detail Page

### PR DESCRIPTION
**Pull request by idk-mr4tyunjay**
#### Overview
This pull request introduces changes to the Albums feature in the application as suggested in issue #1 . The key modifications include the addition of an album detail page, and the restructuring of components for better organization and maintainability.

#### Changes Made

1. **Album Detail Page**:
   - Created a new dynamic route `[id].tsx` to handle album detail views.
   - Implemented the `AlbumDetails` component to display individual album titles and their associated photos in a grid layout.
   - Integrated a `Link` in the `AlbumItem` to navigate to the corresponding album detail page.

2. **Refactoring Components**:
   - **AlbumItem**: 
     - Introduced a separate component to encapsulate the rendering logic for individual albums, improving code organization and readability.
   - **AlbumList**: 
     - Created an `AlbumList` component to manage and display the collection of albums, enhancing separation of concerns.

3. **Styling Adjustments**:
   - Updated the layout and styling of the album detail view using Tailwind CSS classes for a consistent and responsive design.

4. **Search Functionality**:
   - Improved the search functionality to filter albums based on user input, allowing for a more intuitive user experience.

#### Testing
- Verified that all changes function correctly and the application runs without errors.
- Ensured that navigating to individual album pages works as expected and displays the correct content.

@harshit1142 kindly check and merge the pr 
thank you

### CODE REVIEW

**Review by harshit1142 — APPROVED** [review]

**Comment by harshit1142** [comment]
@idk-mr4tyunjay Excellently Done. 👌

**Comment by harshit1142** [comment]
@idk-mr4tyunjay can you tell me about all the tech stacks used? And also about the run command to run it.

**Comment by idk-mr4tyunjay** [comment]
@harshit1142  I haven't used anything extra and worked with the provided template. There's still a lot more that can be done with it, here’s the info you asked for:

---
### Tech Stacks Used

- **Frontend:**
  - **Next.js**: Framework for server-side rendering and static site generation.
  - **Apollo Client**: For managing GraphQL data.
- **Styling:**
  - **Tailwind CSS**: Utility-first CSS framework for styling.
- **Backend:**
  - **GraphQL**: Query language for APIs.

### Run Command
```bash
npm run dev
```
This command starts the development server for the application.

**Comment by harshit1142** [comment]
@idk-mr4tyunjay Thanks for your contribution.

**Pull request merged**
